name: Compile typst files

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths: ["**/*.typ", ".github/workflows/typst.yml", "bib.yaml"]

permissions:
  contents: write

concurrency:
  group: typst-${{ github.ref_name }} 
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TYPST_FONT_PATHS: .
      TYPST_ROOT: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Setup Typstyle
        uses: taiki-e/install-action@v2
        with:
          tool: typstyle

      - name: Format Typst files
        run: typstyle --inplace .

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Format code
          add: '*.typ'

      - name: Compile rapport
        run: typst compile rapport/main.typ

      - name: Compile slides
        run: typst compile slides/main.typ

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update PDFs
          add: '*.pdf pages_count'
